package com.estock.company.entities;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Company")
public class Company {	
	@DynamoDBHashKey
	@DynamoDBAttribute
	private String companyCode;
	@DynamoDBAttribute
    private String companyName;
	@DynamoDBAttribute
    private String companyCEO;
	@DynamoDBAttribute
    private String companyWebsite;
	@DynamoDBAttribute
    private int companyTurnover;
	@DynamoDBAttribute
    private String stockExchange;
	
	public String getCompanyCode() {
		return companyCode;
	}
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	public String getCompanyname() {
		return companyName;
	}
	public void setCompanyname(String companyname) {
		this.companyName = companyname;
	}
	public String getCompanyCEO() {
		return companyCEO;
	}
	public void setCompanyCEO(String companyCEO) {
		this.companyCEO = companyCEO;
	}
	public String getCompanyWebsite() {
		return companyWebsite;
	}
	public void setCompanyWebsite(String companyWebsite) {
		this.companyWebsite = companyWebsite;
	}
	public int getCompanyTurnover() {
		return companyTurnover;
	}
	public void setCompanyTurnover(int companyTurnover) {
		this.companyTurnover = companyTurnover;
	}
	public String getStockExchange() {
		return stockExchange;
	}
	public void setStockExchange(String stockExchange) {
		this.stockExchange = stockExchange;
	}
    
    
}
